/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package autorennen;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
    
/**
 *
 * @author bbsuser
 */
public class MainMenu extends javax.swing.JFrame implements KeyListener {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        
        Auto autoSpieler1 = new Auto(this.spielerName1.getText());
        Auto autoSpieler2 = new Auto(this.spielerName2.getText());

        this.tankFuellung1.setValue(100);
        this.tankFuellung2.setValue(100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        spielerName1 = new javax.swing.JLabel();
        spielerName2 = new javax.swing.JLabel();
        tankFuellung2 = new javax.swing.JProgressBar();
        tankFuellung1 = new javax.swing.JProgressBar();
        streckeSpieler1 = new javax.swing.JPanel();
        streckeSpieler2 = new javax.swing.JPanel();
        bremsen2 = new javax.swing.JButton();
        bremsen1 = new javax.swing.JButton();
        gasGeben2 = new javax.swing.JButton();
        gasGeben1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        countdown = new javax.swing.JLabel();
        weiter1 = new javax.swing.JButton();
        fertig = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        spielerName1.setText("SPIELER 1");

        spielerName2.setText("SPIELER 2");

        tankFuellung2.setOrientation(1);

        tankFuellung1.setOrientation(1);

        streckeSpieler1.setBackground(new java.awt.Color(255, 0, 240));

        javax.swing.GroupLayout streckeSpieler1Layout = new javax.swing.GroupLayout(streckeSpieler1);
        streckeSpieler1.setLayout(streckeSpieler1Layout);
        streckeSpieler1Layout.setHorizontalGroup(
            streckeSpieler1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        streckeSpieler1Layout.setVerticalGroup(
            streckeSpieler1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        streckeSpieler2.setBackground(new java.awt.Color(255, 0, 240));

        javax.swing.GroupLayout streckeSpieler2Layout = new javax.swing.GroupLayout(streckeSpieler2);
        streckeSpieler2.setLayout(streckeSpieler2Layout);
        streckeSpieler2Layout.setHorizontalGroup(
            streckeSpieler2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        streckeSpieler2Layout.setVerticalGroup(
            streckeSpieler2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );

        bremsen2.setText("Bremsen");
        bremsen2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bremsen2ActionPerformed(evt);
            }
        });

        bremsen1.setText("Bremsen");

        gasGeben2.setText("Gas geben");
        gasGeben2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gasGeben2ActionPerformed(evt);
            }
        });

        gasGeben1.setText("Gas geben");
        gasGeben1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gasGeben1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Gewinner: \"ICH\"");

        countdown.setText("3, 2, 1");

        weiter1.setText("weiter");

        fertig.setText("fertig");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(spielerName1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(tankFuellung1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(bremsen1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(gasGeben1))))
                    .addComponent(weiter1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(streckeSpieler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(countdown)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(streckeSpieler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(spielerName2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fertig, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(bremsen2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gasGeben2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tankFuellung2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spielerName1)
                    .addComponent(spielerName2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tankFuellung2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tankFuellung1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(bremsen1)
                                .addGap(82, 82, 82)
                                .addComponent(gasGeben1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(bremsen2)
                        .addGap(77, 77, 77)
                        .addComponent(gasGeben2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(fertig, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(weiter1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 32, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(294, 294, 294)
                .addComponent(countdown)
                .addGap(73, 73, 73))
            .addComponent(streckeSpieler2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(streckeSpieler1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gasGeben2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gasGeben2ActionPerformed
        this.tankFuellung2.setValue((this.tankFuellung2.getValue() - 1));
    }//GEN-LAST:event_gasGeben2ActionPerformed

    private void gasGeben1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gasGeben1ActionPerformed
        this.tankFuellung1.setValue((this.tankFuellung1.getValue() - 1));
    }//GEN-LAST:event_gasGeben1ActionPerformed

    private void bremsen2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bremsen2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bremsen2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bremsen1;
    private javax.swing.JButton bremsen2;
    private javax.swing.JLabel countdown;
    private javax.swing.JButton fertig;
    private javax.swing.JButton gasGeben1;
    private javax.swing.JButton gasGeben2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel spielerName1;
    public javax.swing.JLabel spielerName2;
    private javax.swing.JPanel streckeSpieler1;
    private javax.swing.JPanel streckeSpieler2;
    private javax.swing.JProgressBar tankFuellung1;
    private javax.swing.JProgressBar tankFuellung2;
    private javax.swing.JButton weiter1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent ke) {
                if (ke.getKeyCode() == KeyEvent.VK_S) {
            System.out.println("Gedrückt");
        }
    }

    @Override
    public void keyPressed(KeyEvent ke) {
        if (ke.getKeyCode() == KeyEvent.VK_S) {
            System.out.println("Gedrückt");
        }
    }

    @Override
    public void keyReleased(KeyEvent ke) {
                if (ke.getKeyCode() == KeyEvent.VK_S) {
            System.out.println("Gedrückt");
        }
    }
}
